### ISSUE TITLE
Terminal mode does not react to "\r"

### ISSUE THREAD

**Issue by somethingwithelectronics** [microsoft/vscode-serial-monitor#100]
Hello;

first of all thanks for the great extention and I really like the new terminal mode.
But I am observing a behavior which I am unsure about if it is intended like this.
It seems that the terminal does not react to "\r" or CR if it receives it from the serial port.

My application reacts to a backspace with
` "\r                                                " & "\rSTRING_MINUS_LAST_CHAR"`

which results in the following output 

`test_string`
 press backspace
`test_string                                                test_strin`

Best regards and thanks for your work

_Originally posted by @somethingwithelectronics in https://github.com/microsoft/vscode-serial-monitor/issues/82#issuecomment-1534710905_

**Comment by gcampbell-msft** [comment]
@somethingwithelectronics Thanks for posting this!

To clarify the behavior that you're seeing, if you type `test string` and then hit backspace, the output in your terminal is 
`test_string                                                                       test_strin`?

**Comment by somethingwithelectronics** [comment]
Yes,
my application is running on an embedded system and is connected via an USB serial cable. 
When it receives a backspace cmd, it tries to set the curser to the beginning of the line, clear the line with whitespaces, reset the cursor again to the beginning and print the previous text minus the last character.

Other cmds in my application like ArrowUp use " \r " as well and have a similar behavior and output.

**Comment by gcampbell-msft** [comment]
@somethingwithelectronics A new pre-release version that has slightly more logging will come out tomorrow. 

When that releases, could you do the following?

1. Navigate to your VSCode settings and set the vscode-serial-monitor.loggingVerbosity setting to "debug".
2. Reproduce your scenario.
3. Navigate to the Serial Monitor Logging output pane
4. Copy the text in the output into a file, and send the file here. This will help me debug and diagnose!

NOTE: If you search the Serial Monitor Logging output pane and don't see "Received input into terminal:", could you restart VSCode and then try the above steps again? 

Thanks!

**Comment by gcampbell-msft** [comment]
@somethingwithelectronics I have confirmed that the above repro steps should be available on the most recent pre-release version v0.9.230516001. I look forward to hearing from you!

**Comment by somethingwithelectronics** [comment]
@gcampbell-msft 

Attached you can find the log file. 
Hope it helps you. If you need more, let me know.

[COM3_2023_05_22.14.31.05.923.txt](https://github.com/microsoft/vscode-serial-monitor/files/11531066/COM3_2023_05_22.14.31.05.923.txt)

**Comment by gcampbell-msft** [comment]
@somethingwithelectronics Could you try the steps I listed out above again and ensure that you're copying from the "Serial Monitor Logging" pane of the Output Pane? 

I only see a couple lines of garbled data from the file you linked. I wonder if you grabbed the log file of your serial monitor output, rather than the debugging output of the extension itself, which goes into the Serial Monitor Logging Output pane? 

Thanks!

**Comment by somethingwithelectronics** [comment]
@gcampbell-msft
You are right, I gave you the wrong output.
I have found the debug output now, so I hope the new attachted file is more helpful.

[SerMon_Debug_Output_CR.txt](https://github.com/microsoft/vscode-serial-monitor/files/11562383/SerMon_Debug_Output_CR.txt)

**Comment by gcampbell-msft** [comment]
@somethingwithelectronics Thanks for posting that! We will take a look, investigate, and see if we can diagnose a problem and solution. Thanks again!

**Comment by gcampbell-msft** [comment]
Hi, @somethingwithelectronics ! I just merged a fix for your issue and it should be in pre-release tomorrow! 

Once it goes into pre-release and you are able to test and confirm, please let me know if it works for you!

**Comment by somethingwithelectronics** [comment]
Hi, @gcampbell-msft 
I have tested the newest pre-release and it resolves the problem.
Everything works as expected. 
Thanks a lot for the work and this nice extention.

**Comment by Frenk012** [comment]
Hi @gcampbell-msft, i'm coding in c++ and reading the serial data coming from an arduino mega, and for me the problem is still there, the monitor doesn't recognize the "\r" when i print it in the serial. I searched a lot but nothing helped me, can you?
