### ISSUE TITLE
The serial log is strange. The sequence is broken.

### ISSUE THREAD

**Issue by moran991231** [microsoft/vscode-serial-monitor#110]
The text which sender sent appears in the serial monitor alright, but the log is strange. The sequence is mashed up.  
For example, if a sender send "aaa bbb ccc ddd eee fff\n" periodically, then the log is like...  
* What I expected
```
aaa bbb ccc ddd eee fff
aaa bbb ccc ddd eee fff
aaa bbb ccc ddd eee fff
aaa bbb ccc ddd eee fff
```

* What I recived actually (the 2nd line is strange)
```
aaa bbb ccc ddd eee fff
aaa ccbbb c ddd effee ff 
aaa bbb ccc ddd eee fff
aaa bbb ccc ddd eee fff
```

**I watched the serial monitor window in the VSCode and it worked wonderfully.
However, the log was totally mess.**

Type: Bug Report

**Describe the bug**
- OS and Version: Win10
- VS Code Version: 1.78.2
- Serial Monitor Extension Version: latest release version and pre-release version
- Target embedded device: 
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Code sample and logs**
- Code sample
- `launch.json`

**Screenshots**

**Additional context**

**Comment by moran991231** [comment]
Exactly. The output terminal looks so nice, but the log file (*.txt) doesn't.

**Comment by gcampbell-msft** [comment]
@moran991231 Understood, we will put this bug on our backlog and work to investigate it, thanks for notifying us!

**Comment by gcampbell-msft** [comment]
@moran991231 A couple of questions to help me not only understand the problem, but also to help attempt to reproduce the issue.

1. Does this happen consistently every time that you try to log to a file? 
2. Is there specific hardware that you're running this on? I attempted to create a rough repro on an Arduino, and I am not able to reproduce, the log file looks correct and matches that of the Serial Monitor output. 

Thank you! Any information would be helpful to try and diagnose this issue.

**Comment by moran991231** [comment]
Okay.
Im using an ADuCM3029. it provide an micro USB Uart port, so I uses it. On the other hand, I also use a bluetooth module(df-bluetooth v3) with it. Well, known issues are that the bit duration of UART is not precise and the connection is unstable. I usually use 115200 baud rate, but the actual br is different. I tried to match the actual br(116000) with your tool but it didnt make any difference. The Bluetooth module provided a perfect connection solution, but the inconsistent log occurred continuously anyway.   

1. Yes. I found the UART thru bluetooth was better, but the problem always exists.
2. Im using ADuCm3029. Umm... I found the log goes worse when I sent long data in a short time.

**Comment by moran991231** [comment]
In addition, I couldn't find any regular features of garbled log, such as the error location or a cycle period.
And.... the error doesn't affect other lines. I mean, a garbled line looks has no relation with other lines. (Check up is needed to clarify this situation)  
The most strange point is the output of serial monitor looks very clear. 🤔

**Comment by moran991231** [comment]
I'll try to catch the error and attach the result here for you.
Thx.

**Comment by moran991231** [comment]
Hello. I brought a test result.  
The code was like below. (The below is just pseudo-code)
```c
for(int i = 0; i<500; i++){
    print ("\x1b[0m"    " Hello! "    "\x1b[34m"   " This is a test. "     "\x1b[33m"     "[%d] "     "\r\n",  i);
    delay_a_few_ms();
}
```  
And then, the actual result was ...
![image](https://github.com/microsoft/vscode-serial-monitor/assets/55349869/b8b97b27-730e-405a-bc7b-05f10a88bf60) 
The top half of the image: log file.  
The bottom half: serial monitor.

**Comment by gcampbell-msft** [comment]
@moran991231 Thanks for the additional in-depth information! I have added this to our backlog for the next release and will investigate implementing a fix before then, thanks!

**Comment by gcampbell-msft** [comment]
Hi, @moran991231 ! I have merged a fix for the issue and it should be available in pre-release tomorrow!

Once it is available, please try it out and let me know if it fixes your issue!

**Comment by moran991231** [comment]
Hi, @gcampbell-msft   
I checked it out, but the issue wasn't fixed.
Btw,  is `v0.10.230630001` the latest pre-release version? (I used the version.)   

I'd like to suggest a solution: to save the entire text in the serial monitor. or copy the text.
Now I can use just two functions (`Copy` and `Clear Output`) with the mouse right-click menu.   
It's hard to select the whole text by dragging mouse cursor.  
It will be so nice if this tool provides a cool function to do selcet -> copy -> paste (on notepade) -> save (a log.txt file) at once.  

![image](https://github.com/microsoft/vscode-serial-monitor/assets/55349869/2322f72f-6ee1-4f66-8e23-9939c40a77d7)

I appreciate your efforts! Thx.

**Comment by gcampbell-msft** [comment]
@moran991231 Thanks for testing, I believe you are correct about the most recent of the pre-release. 

Could you reproduce your issues with debugging enabled and then send me the log? This may help me investigate where the issues are getting introduced with logging to a file. 

You can enable this by setting the VSCode setting `vscode-serial-monitor.loggingVerbosity` to `debug`. Then, reproduce your scenario. You should then see lots of output in the "Serial Monitor Logging" Output pane. Please copy this into a file and drop it here. 

Thank you!

**Comment by moran991231** [comment]
Hi,  
I reproduced the issue and brought the logs.
![image](https://github.com/microsoft/vscode-serial-monitor/assets/55349869/3bcdd3de-5e34-46c5-9bbd-80caff82cec7)


[COM31_2023_07_10.10.12.05.161.txt](https://github.com/microsoft/vscode-serial-monitor/files/11996891/COM31_2023_07_10.10.12.05.161.txt)  
[debug_output.txt](https://github.com/microsoft/vscode-serial-monitor/files/11996893/debug_output.txt)  
[serial_monitor_output.txt](https://github.com/microsoft/vscode-serial-monitor/files/11996894/serial_monitor_output.txt)

**Comment by gcampbell-msft** [comment]
@moran991231 I have a possible fix, though I'm not 100% sure, I could use your assistance with testing it. 

Could you please manually install this vsix: First, download the zip and modify the `.zip` extension to `.vsix`, then: Go to extensions pane, click the three dots in the upper right, click "Install from VSIX", and test and let me know if this fixes your issue? 

[vscode-serial-monitor.zip](https://github.com/microsoft/vscode-serial-monitor/files/12002215/vscode-serial-monitor.zip)

**Comment by moran991231** [comment]
@gcampbell-msft  
Hi  
The test is being delayed because of my schedule.

**Comment by gcampbell-msft** [comment]
@moran991231 Hi! I'm just checking in on whether you've been able to test? I understand that you are busy, so it's no pressure, I just wanted to check. 

Thanks!

**Comment by gsarenas** [comment]
Hello @gcampbell-msft. I ran into the same problem today. Were you ever able to find a solution?

Here's my SERIAL MONITOR view:
![bugSERIALMONITOR](https://github.com/microsoft/vscode-serial-monitor/assets/55554604/a57210bf-0465-4e40-bfe5-9cef3536ff20)

Here's the log file:
![bugLOGGING](https://github.com/microsoft/vscode-serial-monitor/assets/55554604/7dedd323-1d37-4756-bb50-998e708de3a5)

**Comment by gcampbell-msft** [comment]
@gsarenas What version of the extension are you on?

**Comment by gsarenas** [comment]
@gcampbell-msft v0.10.231102001

**Comment by MM-Lehmann** [comment]
I must object. It is NOT fixed. Also see issue #199 
Please reopen

**Comment by gcampbell-msft** [comment]
@MM-Lehmann Thanks for following up, since #199 has the same issue, we'll leave this closed.
